### PR TITLE
Start logging to db

### LINKED ISSUE #9: Save logs to db
Create a new table with two columns: timestamp, logs?

Which logs to save? At least if import or run analysis have failed.

### PR DESCRIPTION
**Pull request by Divinare**
Closes #9

### CODE REVIEW

**Comment by Divinare** [comment]
This can be reviewed now.

**Comment by datarttu** [comment]
Added some commits to suggest a restructured approach to DB logging.

*Still TODO:*

* Remove `logger` dependencies from other functions under importer/main.
* Apply the changed logging logic to run_analysis.py

File: db/sql/105_logs.sql [hunk 1]
```diff
@@ -0,0 +1,32 @@
...
+  log_level        text          PRIMARY KEY
+);
+COMMENT ON TABLE logs.log_level IS
+'Log levels allowed for log tables log_level values.';
+INSERT INTO logs.log_level (log_level)
+VALUES ('info'), ('warning'), ('error'), ('debug');
+
+CREATE TABLE logs.importer_log (
+  id bigserial PRIMARY KEY,
+  timestamp timestamptz DEFAULT now(),
```
Comment (datarttu) [inline db/sql/105_logs.sql:18]: This is not critical, but I'd rather use `log_timestamp` as a field name, like it was in the first commit introducing this schema I think. As a general practice, it's safer not to use Postgres keywords (`timestamp` is a data type) as identifiers, to avoid parsing and human errors. Sorry for missing this in my first review.

The same goes for `api_log` below.

File: python/importer/main.py [hunk 2]
```diff
@@ -1,66 +1,94 @@
...
 from .run_analysis import main as run_analysis
 
 # TODO: import other event types as well when needed.
 event_types_to_import = ['DOC', 'DOO']
 
-def main(dataImporter: func.TimerRequest):
-    logger = get_logger()
+def main(importer: func.TimerRequest, context: func.Context):
+    # Taken from: https://stackoverflow.com/a/879937/4282381
+    class AnalyticsLoggingFilter(logging.Filter):
```
Comment (datarttu) [inline python/importer/main.py:21]: I think this is very OK for now - or, instead of a class we could also use a [factory function](https://rmcomplexity.com/article/2020/12/01/introduction-to-python-logging.html#custom-filter-example), but that's rather a matter of taste so don't worry about it too much. Anyway I think this class is worth moving under `common.logger_util` from where we can import it. This way `main()` remains a bit tidier (still with the logging boilerplate though), and this `'main'`-based filter could also be useful in possible future routines run similarly as `main`.

**Review by datarttu — APPROVED** [review]
I think this is good work and ready to be merged, but feel free to check out my suggestions that are rather tiny things. 👍
